//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBlog.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string _0__days {
            get {
                return ResourceManager.GetString("{0} days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year(s) and {1} month(s).
        /// </summary>
        public static string _0__year_s__and__1__month_s_ {
            get {
                return ResourceManager.GetString("{0} year(s) and {1} month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Blog comment notification] Re: {0}.
        /// </summary>
        public static string _Blog_comment_notification__Re___0_ {
            get {
                return ResourceManager.GetString("[Blog comment notification] Re: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day.
        /// </summary>
        public static string a_day {
            get {
                return ResourceManager.GetString("a day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the page does not exist, you can.
        /// </summary>
        public static string Access_to_the_page_does_not_exist__you_can {
            get {
                return ResourceManager.GetString("Access to the page does not exist, you can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string Add_category {
            get {
                return ResourceManager.GetString("Add category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add comment.
        /// </summary>
        public static string add_comment {
            get {
                return ResourceManager.GetString("add comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to.
        /// </summary>
        public static string Add_to {
            get {
                return ResourceManager.GetString("Add to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add welcome topic.
        /// </summary>
        public static string Add_welcome_topic {
            get {
                return ResourceManager.GetString("Add welcome topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After all the operations have been completed, the Save button will take effect.
        /// </summary>
        public static string After_all_the_operations_have_been_completed__the_Save_button_will_take_effect {
            get {
                return ResourceManager.GetString("After all the operations have been completed, the Save button will take effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the article.
        /// </summary>
        public static string After_the_article {
            get {
                return ResourceManager.GetString("After the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias(optional).
        /// </summary>
        public static string Alias_optional_ {
            get {
                return ResourceManager.GetString("Alias(optional)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow comment.
        /// </summary>
        public static string Allow_comment {
            get {
                return ResourceManager.GetString("Allow comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve comments.
        /// </summary>
        public static string Approve_comments {
            get {
                return ResourceManager.GetString("Approve comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved comments.
        /// </summary>
        public static string Approved_comments {
            get {
                return ResourceManager.GetString("Approved comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete comments?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_comments_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete comments?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the article?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_the_article_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete the article?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article does not exist.
        /// </summary>
        public static string Article_does_not_exist {
            get {
                return ResourceManager.GetString("Article does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article does not exists.
        /// </summary>
        public static string Article_does_not_exists {
            get {
                return ResourceManager.GetString("Article does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available widgets.
        /// </summary>
        public static string Available_widgets {
            get {
                return ResourceManager.GetString("Available widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string Bad_request {
            get {
                return ResourceManager.GetString("Bad request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before the article.
        /// </summary>
        public static string Before_the_article {
            get {
                return ResourceManager.GetString("Before the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog address.
        /// </summary>
        public static string Blog_address {
            get {
                return ResourceManager.GetString("Blog address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog has been already installed.
        /// </summary>
        public static string Blog_has_been_already_installed {
            get {
                return ResourceManager.GetString("Blog has been already installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Host.
        /// </summary>
        public static string Blog_Host {
            get {
                return ResourceManager.GetString("Blog Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Title.
        /// </summary>
        public static string Blog_Title {
            get {
                return ResourceManager.GetString("Blog Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the publish.
        /// </summary>
        public static string Cancel_the_publish {
            get {
                return ResourceManager.GetString("Cancel the publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the reply to the message.
        /// </summary>
        public static string Cancel_the_reply_to_the_message {
            get {
                return ResourceManager.GetString("Cancel the reply to the message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}.
        /// </summary>
        public static string Category___0_ {
            get {
                return ResourceManager.GetString("Category: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exists.
        /// </summary>
        public static string Category_does_not_exists {
            get {
                return ResourceManager.GetString("Category does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category.
        /// </summary>
        public static string Choose_category {
            get {
                return ResourceManager.GetString("Choose category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close comment after.
        /// </summary>
        public static string Close_comment_after {
            get {
                return ResourceManager.GetString("Close comment after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment not exists.
        /// </summary>
        public static string Comment_not_exists {
            get {
                return ResourceManager.GetString("Comment not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments ({0}).
        /// </summary>
        public static string comments___0__ {
            get {
                return ResourceManager.GetString("comments ({0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments not allow for this articles.
        /// </summary>
        public static string Comments_not_allow_for_this_articles {
            get {
                return ResourceManager.GetString("Comments not allow for this articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirm_new_password {
            get {
                return ResourceManager.GetString("Confirm new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of the error page.
        /// </summary>
        public static string Content_of_the_error_page {
            get {
                return ResourceManager.GetString("Content of the error page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom code.
        /// </summary>
        public static string Custom_code {
            get {
                return ResourceManager.GetString("Custom code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the message, but leave the reply.
        /// </summary>
        public static string Delete_the_message__but_leave_the_reply {
            get {
                return ResourceManager.GetString("Delete the message, but leave the reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the message and reply.
        /// </summary>
        public static string Delete_the_message_and_reply {
            get {
                return ResourceManager.GetString("Delete the message and reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did you forget your password?.
        /// </summary>
        public static string did_you_forget_your_password_ {
            get {
                return ResourceManager.GetString("did you forget your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetBlog.
        /// </summary>
        public static string DotNetBlog {
            get {
                return ResourceManager.GetString("DotNetBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft was saved successfully.
        /// </summary>
        public static string Draft_was_saved_successfully {
            get {
                return ResourceManager.GetString("Draft was saved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate category name.
        /// </summary>
        public static string Duplicate_category_name {
            get {
                return ResourceManager.GetString("Duplicate category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated email address.
        /// </summary>
        public static string Duplicated_email_address {
            get {
                return ResourceManager.GetString("Duplicated email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string E_mail {
            get {
                return ResourceManager.GetString("E-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string Edit_category {
            get {
                return ResourceManager.GetString("Edit category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the tag.
        /// </summary>
        public static string Edit_the_tag {
            get {
                return ResourceManager.GetString("Edit the tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Editor_Language_Key {
            get {
                return ResourceManager.GetString("Editor_Language_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Re:{0}
        ///&lt;br/&gt;&lt;br/&gt;
        ///{1}
        ///&lt;hr/&gt;
        ///Comment by: &lt;a href=&quot;&quot;mailto://{2}&quot;&quot; target=&quot;&quot;_blank&quot;&quot;&gt;{3}&lt;/a&gt;
        ///&lt;br/&gt;
        ///URL: &lt;a href=&quot;&quot;{4}&quot;&quot; target=&quot;&quot;_blank&quot;&quot;&gt;{4}&lt;/a&gt;.
        /// </summary>
        public static string Email_NewComment {
            get {
                return ResourceManager.GetString("Email_NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        public static string Enable_SSL {
            get {
                return ResourceManager.GetString("Enable SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable website comment.
        /// </summary>
        public static string Enable_website_comment {
            get {
                return ResourceManager.GetString("Enable website comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the blog address(URL).
        /// </summary>
        public static string Enter_the_blog_address_URL_ {
            get {
                return ResourceManager.GetString("Enter the blog address(URL)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the content here.
        /// </summary>
        public static string Enter_the_content_here {
            get {
                return ResourceManager.GetString("Enter the content here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keyword for search.
        /// </summary>
        public static string Enter_the_keyword_for_search {
            get {
                return ResourceManager.GetString("Enter the keyword for search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keyword search.
        /// </summary>
        public static string Enter_the_keyword_search {
            get {
                return ResourceManager.GetString("Enter the keyword search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error page.
        /// </summary>
        public static string Error_page {
            get {
                return ResourceManager.GetString("Error page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error page title.
        /// </summary>
        public static string Error_page_title {
            get {
                return ResourceManager.GetString("Error page title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to footer script.
        /// </summary>
        public static string footer_script {
            get {
                return ResourceManager.GetString("footer script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to the last page.
        /// </summary>
        public static string Go_back_to_the_last_page {
            get {
                return ResourceManager.GetString("Go back to the last page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to article.
        /// </summary>
        public static string Go_to_article {
            get {
                return ResourceManager.GetString("Go to article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the page.
        /// </summary>
        public static string Go_to_the_page {
            get {
                return ResourceManager.GetString("Go to the page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header script.
        /// </summary>
        public static string Header_script {
            get {
                return ResourceManager.GetString("Header script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string Hello_world {
            get {
                return ResourceManager.GetString("Hello world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        public static string In_use {
            get {
                return ResourceManager.GetString("In use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page content, please enter valid content.
        /// </summary>
        public static string Invalid_page_content__please_enter_valid_content {
            get {
                return ResourceManager.GetString("Invalid page content, please enter valid content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page title.
        /// </summary>
        public static string Invalid_page_title {
            get {
                return ResourceManager.GetString("Invalid page title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string Invalid_request {
            get {
                return ResourceManager.GetString("Invalid request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request, please try again later.
        /// </summary>
        public static string Invalid_request__please_try_again_later {
            get {
                return ResourceManager.GetString("Invalid request, please try again later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is displayed in the list.
        /// </summary>
        public static string Is_displayed_in_the_list {
            get {
                return ResourceManager.GetString("Is displayed in the list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk comments.
        /// </summary>
        public static string Junk_comments {
            get {
                return ResourceManager.GetString("Junk comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string Keep_me_logged_in {
            get {
                return ResourceManager.GetString("Keep me logged in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest comments.
        /// </summary>
        public static string Latest_comments {
            get {
                return ResourceManager.GetString("Latest comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login blog.
        /// </summary>
        public static string Login_blog {
            get {
                return ResourceManager.GetString("Login blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the password is not inconsistent.
        /// </summary>
        public static string Make_sure_the_password_is_not_inconsistent {
            get {
                return ResourceManager.GetString("Make sure the password is not inconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managment categories.
        /// </summary>
        public static string Managment_categories {
            get {
                return ResourceManager.GetString("Managment categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of tag in clouds.
        /// </summary>
        public static string Maximum_number_of_tag_in_clouds {
            get {
                return ResourceManager.GetString("Maximum number of tag in clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of articles per tag.
        /// </summary>
        public static string Minimum_number_of_articles_per_tag {
            get {
                return ResourceManager.GetString("Minimum number of articles per tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMMM}.
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the configuration.
        /// </summary>
        public static string Modify_the_configuration {
            get {
                return ResourceManager.GetString("Modify the configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should be between {0} - {1}.
        /// </summary>
        public static string New_password_should_be_between__0_____1_ {
            get {
                return ResourceManager.GetString("New password should be between {0} - {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email specified.
        /// </summary>
        public static string No_email_specified {
            get {
                return ResourceManager.GetString("No email specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limitation.
        /// </summary>
        public static string No_limitation {
            get {
                return ResourceManager.GetString("No limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported language.
        /// </summary>
        public static string Not_supported_language {
            get {
                return ResourceManager.GetString("Not supported language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when there is a comment.
        /// </summary>
        public static string Notify_me_when_there_is_a_comment {
            get {
                return ResourceManager.GetString("Notify me when there is a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of articles per page.
        /// </summary>
        public static string Number_of_articles_per_page {
            get {
                return ResourceManager.GetString("Number of articles per page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of articles published.
        /// </summary>
        public static string Number_of_articles_published {
            get {
                return ResourceManager.GetString("Number of articles published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string Number_of_pages {
            get {
                return ResourceManager.GetString("Number of pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages published.
        /// </summary>
        public static string Number_of_pages_published {
            get {
                return ResourceManager.GetString("Number of pages published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Old_password {
            get {
                return ResourceManager.GetString("Old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful.
        /// </summary>
        public static string Operation_successful {
            get {
                return ResourceManager.GetString("Operation successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or search for other resources.
        /// </summary>
        public static string or_search_for_other_resources {
            get {
                return ResourceManager.GetString("or search for other resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page description.
        /// </summary>
        public static string Page_description {
            get {
                return ResourceManager.GetString("Page description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent does not exists.
        /// </summary>
        public static string Parent_does_not_exists {
            get {
                return ResourceManager.GetString("Parent does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending comments.
        /// </summary>
        public static string Pending_comments {
            get {
                return ResourceManager.GetString("Pending comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending for review.
        /// </summary>
        public static string Pending_for_review {
            get {
                return ResourceManager.GetString("Pending for review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendings.
        /// </summary>
        public static string Pendings {
            get {
                return ResourceManager.GetString("Pendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Personal_Information {
            get {
                return ResourceManager.GetString("Personal Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your password.
        /// </summary>
        public static string Please_check_your_password {
            get {
                return ResourceManager.GetString("Please check your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a category name.
        /// </summary>
        public static string Please_enter_a_category_name {
            get {
                return ResourceManager.GetString("Please enter a category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a nickname.
        /// </summary>
        public static string Please_enter_a_nickname {
            get {
                return ResourceManager.GetString("Please enter a nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        public static string Please_enter_a_valid_email {
            get {
                return ResourceManager.GetString("Please enter a valid email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct number of comments.
        /// </summary>
        public static string Please_enter_correct_number_of_comments {
            get {
                return ResourceManager.GetString("Please enter correct number of comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct port number.
        /// </summary>
        public static string Please_enter_correct_port_number {
            get {
                return ResourceManager.GetString("Please enter correct port number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of comments.
        /// </summary>
        public static string Please_enter_number_of_comments {
            get {
                return ResourceManager.GetString("Please enter number of comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the blog host.
        /// </summary>
        public static string Please_enter_the_blog_host {
            get {
                return ResourceManager.GetString("Please enter the blog host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the blog title.
        /// </summary>
        public static string Please_enter_the_blog_title {
            get {
                return ResourceManager.GetString("Please enter the blog title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the content.
        /// </summary>
        public static string Please_enter_the_content {
            get {
                return ResourceManager.GetString("Please enter the content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the content of the article.
        /// </summary>
        public static string Please_enter_the_content_of_the_article {
            get {
                return ResourceManager.GetString("Please enter the content of the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct number of articles.
        /// </summary>
        public static string Please_enter_the_correct_number_of_articles {
            get {
                return ResourceManager.GetString("Please enter the correct number of articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name.
        /// </summary>
        public static string Please_enter_the_name {
            get {
                return ResourceManager.GetString("Please enter the name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of articles.
        /// </summary>
        public static string Please_enter_the_number_of_articles {
            get {
                return ResourceManager.GetString("Please enter the number of articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the page content.
        /// </summary>
        public static string Please_enter_the_page_content {
            get {
                return ResourceManager.GetString("Please enter the page content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the page title.
        /// </summary>
        public static string Please_enter_the_page_title {
            get {
                return ResourceManager.GetString("Please enter the page title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the title.
        /// </summary>
        public static string Please_enter_the_title {
            get {
                return ResourceManager.GetString("Please enter the title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the title of the article.
        /// </summary>
        public static string Please_enter_the_title_of_the_article {
            get {
                return ResourceManager.GetString("Please enter the title of the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter username.
        /// </summary>
        public static string please_enter_username {
            get {
                return ResourceManager.GetString("please enter username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string Please_enter_your_email {
            get {
                return ResourceManager.GetString("Please enter your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your nickname.
        /// </summary>
        public static string Please_enter_your_nickname {
            get {
                return ResourceManager.GetString("Please enter your nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter your password.
        /// </summary>
        public static string please_enter_your_password {
            get {
                return ResourceManager.GetString("please enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter your username.
        /// </summary>
        public static string please_enter_your_username {
            get {
                return ResourceManager.GetString("please enter your username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the comments.
        /// </summary>
        public static string Please_fill_in_the_comments {
            get {
                return ResourceManager.GetString("Please fill in the comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the name.
        /// </summary>
        public static string Please_fill_in_the_name {
            get {
                return ResourceManager.GetString("Please fill in the name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the reply.
        /// </summary>
        public static string Please_fill_in_the_reply {
            get {
                return ResourceManager.GetString("Please fill in the reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the default language.
        /// </summary>
        public static string Please_select_the_default_language {
            get {
                return ResourceManager.GetString("Please select the default language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        public static string Please_sign_in {
            get {
                return ResourceManager.GetString("Please sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type correct email address.
        /// </summary>
        public static string Please_type_correct_email_address {
            get {
                return ResourceManager.GetString("Please type correct email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your email.
        /// </summary>
        public static string Please_type_your_email {
            get {
                return ResourceManager.GetString("Please type your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload the correct format image file.
        /// </summary>
        public static string Please_upload_the_correct_format_image_file {
            get {
                return ResourceManager.GetString("Please upload the correct format image file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number.
        /// </summary>
        public static string Port_number {
            get {
                return ResourceManager.GetString("Port number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent articles.
        /// </summary>
        public static string Recent_articles {
            get {
                return ResourceManager.GetString("Recent articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent comments.
        /// </summary>
        public static string Recent_comments {
            get {
                return ResourceManager.GetString("Recent comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent drafts.
        /// </summary>
        public static string Recent_drafts {
            get {
                return ResourceManager.GetString("Recent drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to related articles.
        /// </summary>
        public static string related_articles {
            get {
                return ResourceManager.GetString("related articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to comment.
        /// </summary>
        public static string Reply_to_comment {
            get {
                return ResourceManager.GetString("Reply to comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to comment not available.
        /// </summary>
        public static string Reply_to_comment_not_available {
            get {
                return ResourceManager.GetString("Reply to comment not available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an error. Please try again later.
        /// </summary>
        public static string Request_an_error__Please_try_again_later {
            get {
                return ResourceManager.GetString("Request an error. Please try again later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request page is wrong, please try again later....
        /// </summary>
        public static string Request_page_is_wrong_please_try_again_later {
            get {
                return ResourceManager.GetString("Request page is wrong please try again later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to home page.
        /// </summary>
        public static string return_to_home_page {
            get {
                return ResourceManager.GetString("return to home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to the home page.
        /// </summary>
        public static string return_to_the_home_page {
            get {
                return ResourceManager.GetString("return to the home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save comment.
        /// </summary>
        public static string Save_comment {
            get {
                return ResourceManager.GetString("Save comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the draft quickly.
        /// </summary>
        public static string Save_the_draft_quickly {
            get {
                return ResourceManager.GetString("Save the draft quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved drafts.
        /// </summary>
        public static string Saved_drafts {
            get {
                return ResourceManager.GetString("Saved drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string Saved_successfully {
            get {
                return ResourceManager.GetString("Saved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for.
        /// </summary>
        public static string search_for {
            get {
                return ResourceManager.GetString("search for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string Search_result {
            get {
                return ResourceManager.GetString("Search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result: {0}.
        /// </summary>
        public static string Search_result___0_ {
            get {
                return ResourceManager.GetString("Search result: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected parent does not exists.
        /// </summary>
        public static string Selected_parent_does_not_exists {
            get {
                return ResourceManager.GetString("Selected parent does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification via email when received a comment.
        /// </summary>
        public static string Send_notification_via_email_when_received_a_comment {
            get {
                return ResourceManager.GetString("Send notification via email when received a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as homepage.
        /// </summary>
        public static string Set_as_homepage {
            get {
                return ResourceManager.GetString("Set as homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show alias.
        /// </summary>
        public static string Show_alias {
            get {
                return ResourceManager.GetString("Show alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date.
        /// </summary>
        public static string Show_date {
            get {
                return ResourceManager.GetString("Show date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only article summary.
        /// </summary>
        public static string Show_only_article_summary {
            get {
                return ResourceManager.GetString("Show only article summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show RSS Button.
        /// </summary>
        public static string Show_RSS_Button {
            get {
                return ResourceManager.GetString("Show RSS Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show summary.
        /// </summary>
        public static string Show_summary {
            get {
                return ResourceManager.GetString("Show summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the number of articles.
        /// </summary>
        public static string Show_the_number_of_articles {
            get {
                return ResourceManager.GetString("Show the number of articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the number of comments.
        /// </summary>
        public static string Show_the_number_of_comments {
            get {
                return ResourceManager.GetString("Show the number of comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site navigation.
        /// </summary>
        public static string Site_navigation {
            get {
                return ResourceManager.GetString("Site navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP address.
        /// </summary>
        public static string SMTP_address {
            get {
                return ResourceManager.GetString("SMTP address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the system has made an error.
        /// </summary>
        public static string Sorry_the_system_has_made_an_error {
            get {
                return ResourceManager.GetString("Sorry the system has made an error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful operation.
        /// </summary>
        public static string Successful_operation {
            get {
                return ResourceManager.GetString("Successful operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrator.
        /// </summary>
        public static string System_Administrator {
            get {
                return ResourceManager.GetString("System Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: {0}.
        /// </summary>
        public static string Tag___0_ {
            get {
                return ResourceManager.GetString("Tag: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Email.
        /// </summary>
        public static string Test_Email {
            get {
                return ResourceManager.GetString("Test Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email settings.
        /// </summary>
        public static string Test_email_settings {
            get {
                return ResourceManager.GetString("Test email settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test successfully.
        /// </summary>
        public static string Test_successfully {
            get {
                return ResourceManager.GetString("Test successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article does not exists.
        /// </summary>
        public static string The_article_does_not_exists {
            get {
                return ResourceManager.GetString("The article does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label does not exists.
        /// </summary>
        public static string The_label_does_not_exists {
            get {
                return ResourceManager.GetString("The label does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label name is duplicated.
        /// </summary>
        public static string The_label_name_is_duplicated {
            get {
                return ResourceManager.GetString("The label name is duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page does not exists anymore.
        /// </summary>
        public static string The_page_does_not_exists_anymore {
            get {
                return ResourceManager.GetString("The page does not exists anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has encountered an error.
        /// </summary>
        public static string The_server_has_encountered_an_error {
            get {
                return ResourceManager.GetString("The server has encountered an error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the article.
        /// </summary>
        public static string The_title_of_the_article {
            get {
                return ResourceManager.GetString("The title of the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To View.
        /// </summary>
        public static string To_View {
            get {
                return ResourceManager.GetString("To View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust authenticated comment&apos;s users.
        /// </summary>
        public static string Trust_authenticated_comment_s_users {
            get {
                return ResourceManager.GetString("Trust authenticated comment\'s users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaudited comments ({0}).
        /// </summary>
        public static string Unaudited_comments___0__ {
            get {
                return ResourceManager.GetString("Unaudited comments ({0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaudited comments({0}).
        /// </summary>
        public static string Unaudited_comments__0__ {
            get {
                return ResourceManager.GetString("Unaudited comments({0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists.
        /// </summary>
        public static string User_does_not_exists {
            get {
                return ResourceManager.GetString("User does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image.
        /// </summary>
        public static string User_Image {
            get {
                return ResourceManager.GetString("User Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfiy comment.
        /// </summary>
        public static string Verfiy_comment {
            get {
                return ResourceManager.GetString("Verfiy comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string Welcome__0_ {
            get {
                return ResourceManager.GetString("Welcome {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example comment.
        /// </summary>
        public static string Welcome_comment {
            get {
                return ResourceManager.GetString("Welcome comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DotNetBlog.
        /// </summary>
        public static string Welcome_to_DotNetBlog {
            get {
                return ResourceManager.GetString("Welcome to DotNetBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to install DotNetBlog 😊. To modify this content and manage your blog you could open &lt;a href=&quot;/admin&quot;&gt;Admin&lt;/a&gt; Page and login with your username and password..
        /// </summary>
        public static string Welcome_topic_content {
            get {
                return ResourceManager.GetString("Welcome topic content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong paging parameters.
        /// </summary>
        public static string Wrong_paging_parameters {
            get {
                return ResourceManager.GetString("Wrong paging parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string Wrong_password {
            get {
                return ResourceManager.GetString("Wrong password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong reply object.
        /// </summary>
        public static string Wrong_reply_object {
            get {
                return ResourceManager.GetString("Wrong reply object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username and password.
        /// </summary>
        public static string Wrong_username_or_password {
            get {
                return ResourceManager.GetString("Wrong username or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote.
        /// </summary>
        public static string Wrote {
            get {
                return ResourceManager.GetString("Wrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are sure you want to delete comments?.
        /// </summary>
        public static string You_are_sure_you_want_to_delete_comments_ {
            get {
                return ResourceManager.GetString("You are sure you want to delete comments?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string You_can {
            get {
                return ResourceManager.GetString("You can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set as parent.
        /// </summary>
        public static string You_cannot_set_as_parent {
            get {
                return ResourceManager.GetString("You cannot set as parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been added successfully and requires an administrator to approve it before it can be displayed.
        /// </summary>
        public static string Your_comment_has_been_added_successfully_and_requires_an_administrator_to_approve_it_before_it_can_be_displayed {
            get {
                return ResourceManager.GetString("Your comment has been added successfully and requires an administrator to approve" +
                        " it before it can be displayed", resourceCulture);
            }
        }
    }
}
